import '@/config/fontAwesome';
import '@/styles/index.scss';
import './layout.scss';

import { ThemeProvider } from '@mui/material/styles';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';

import theme from './theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
           <ThemeProvider theme={theme}>
              {children}
+           </ThemeProvider>
+        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
