import type { Metadata } from 'next';

import Layout from '../app/layout';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

import type { AppProps } from 'next/app';

export default function MyApp({ Component, pageProps }: AppProps) {
	return (
		<Layout>
			<Component {...pageProps} />
		</Layout>
	);
}
